[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "mkdir -p database",
  "mkdir -p public/images/posts",
  "chmod -R 755 database",
  "chmod -R 755 public/images"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t Layrid-Clone"
