[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.php", "**/*.css", "**/*.js"]

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t Layrid-Clone"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
